### ISSUE TITLE
client disconnected unexpectedly python 3, Django 

### ISSUE THREAD

**Issue by folt** [fanout/django-grip#7]
my views.py
`def echo(request):
    ws = request.wscontext

    if ws.is_opening():
        ws.accept()
        ws.subscribe('room')

    while ws.can_recv():
        message = ws.recv()
        if message is None:
            ws.close()
            break

        ws.send(message)`

When I send a string to the channel "абв" 
Getting an error:
`Internal Server Error: /pushpin/echo/
Traceback (most recent call last):
  File "/Users/folt/Documents/env/api_server/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/folt/Documents/env/api_server/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/folt/Documents/env/api_server/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/folt/Documents/env/api_server/lib/python3.5/site-packages/django_grip.py", line 190, in wrapped_view
    response = view_func(*args, **kwargs)
  File "/Users/folt/Documents/Working/api_server/api_server/apps/api_v1/app_pushpin/views.py", line 69, in echo
    message = ws.recv()
  File "/Users/folt/Documents/env/api_server/lib/python3.5/site-packages/django_grip.py", line 142, in recv
    raise IOError('client disconnected unexpectedly')
OSError: client disconnected unexpectedly
[21/Mar/2017 13:33:32] "POST /pushpin/echo/ HTTP/1.1" 500 69632`

**Comment by jkarneges** [comment]
This is probably due to the use of the `unicode` type in the middleware. Will need to fix that for Python 3.

**Comment by folt** [comment]
You can fix it
Because of this I can not use the library for my project

**Comment by jkarneges** [comment]
This should be fixed now.
